# Site
repository: ratankaliani/ratankaliani.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Ratan Kaliani
title: EECS @ Berkeley | Strategy Consultant @ Venture
email: ratankaliani@berkeley.edu
phone: (571)-620-9135
website: ratankaliani.github.io

# Social links
# twitter_username: jekyllrb
github_username:  ratankaliani
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: ratankaliani
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/hoco.png
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm Ratan Kaliani, an Electrical Engineering & Computer Science (EECS) student at UC Berkeley.
  I'm fascinated by cutting edge of financial technology, artificial intelligence, the Internet of Things and developments in technology around the world!
  
  Looking for <mark>software engineering internships</mark> for the <mark>Summer of 2020</mark>. 

  <mark>What I'm Currently Working On:</mark>
    - Strategy Consultant for Hudl, a sports software company, analyzing UI/UX design and market penetration tactics.
    - Streami, an app that connects strangers who want to watch movies at the theater with other people.
    - Learning the ReactJS framework to prepare for future hackathons.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I love playing basketball and table tennis recreationally, and recently I've been developing
  an affinity for working with crypto and blockchain technologies.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
